name: Deploy to Cloudflare Workers

on:
  repository_dispatch:
  push:
    branches: ['master']

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: Build & Deploy
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'
      - run: yarn install
      - name: Publish
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          preCommands: |
            echo "*** post commands ***"
            wrangler r2 bucket create turborepo-cache
            echo "******"
          secrets: |
            TURBO_TOKEN
          command: publish
        env:
          TURBO_TOKEN: ${{ secrets.TURBO_TOKEN || 'TURBO_TOKEN_SECRET' }}
          CF_ACCOUNT_ID: ${{secrets.CF_ACCOUNT_ID}}
